This project is geared towards creating a habit tracker to help the user create and maintain healthy habits!

Project Goals:

Bedtime/Wake-up functions: upon the user entering the times that they wish to go to bed and wakeup they should be told
                           how many circadian rhythm cycles they would be getting, and if it's less than the recommended offer a better time to go to sleep!

User Driven goals:         the user would be prompted to enter goals that they want to accomplish and beable to update/change said goal.

Streaks:                   the user will be made aware of how long of a streak they have generated by completing their goals everyday.

User LogIn:                the user should beable to log in so that they can track their progress/ delete account.

